#logging:
#  level.org.springframework.cloud: DEBUG

spring:
  application:
    name: turbine-server
---
spring:
  profiles: development
  rabbitmq:
    host: ${vcap.services.rabbitmq.credentials.hostname:host.pcfdev.io}
    username: ${vcap.services.rabbitmq.credentials.username:user}
    password: ${vcap.services.rabbitmq.credentials.password:pass}

# for self running without config-server on cloud.
---
spring:
  profiles: cloud
  rabbitmq:
    host: ${vcap.services.rabbitmq.credentials.hostname}
    username: ${vcap.services.rabbitmq.credentials.username}
    password: ${vcap.services.rabbitmq.credentials.password}